apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "apm-hub.fullname" . }}-sa
  labels:
    {{- include "apm-hub.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: {{ include "apm-hub.name" . }}-role
rules:
  - apiGroups:
      - ""
    resources:
      - "services"
      - "namespaces"
      - "nodes"
      - "pods"
      - "pods/log"
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - "apps"
      - "extensions"
    resources:
      - "deployments"
    verbs:
      - get
      - list
      - watch
  # For operator
  - apiGroups:
    - apmhub.flanksource.com
    resources:
    - apmhubconfigs
    verbs:
    - create
    - delete
    - get
    - list
    - patch
    - update
    - watch
  - apiGroups:
    - apmhub.flanksource.com
    resources:
    - apmhubconfigs/status
    verbs:
    - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "apm-hub.fullname" . }}-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "apm-hub.name" . }}-role
subjects:
  - kind: ServiceAccount
    name: {{ include "apm-hub.fullname" . }}-sa
    namespace: {{ .Release.Namespace }}
