backends:
  - kubernetes:
      kubeconfig:
  - elasticsearch:
      # address: "http://localhost:9200"
      username: "elastic"
      password: "elastic"
      cloudID: "apm:abcdefghijklmnopqrstuvwxyz"
      apiKey: ""
      index: "test"
      query: '
        {
          "query": { 
            "match": { 
              "title": "{{.Title}}" 
            }
          }
        }'
