backends:
  - opensearch:
      address: "https://logs.example.com"
      namespace: "kube"
      fields:
        message: "message"
        timestamp: "@timestamp"
        exclusions:
          - "log"
      username:
        value: "elastic"
      password:
        value: "abcdefghijklmnopqrstuvwxyz"
      index: "my-index-*"
      query: |
        {
          {{if .Page}}"search_after": {{ .Page }},{{end}}
          "sort": [{ "@timestamp": { "order": "desc", "unmapped_type": "boolean" } }],
          "query": {
            "bool": {
              "filter": [
                {"match_phrase": {"transaction.client_ip": "{{index .Labels "clientIP"}}" }},
                {"match_phrase": {"transaction.request.uri": "{{index .Labels "requestURI"}}" }}
              ],
              "must_not":[
                {"match_phrase": { "agent.name": "nginx-ingress-controller-f6zx7" }},
                {"match_phrase": { "agent.name": "nginx-ingress-controller-r46vg" }}
              ]
            }
          }
        }
