backends:
  - file:
      routes:
        - idPrefix: "nginx-"
          labels:
            type: "access"
      labels:
        name: acmehost
        type: Nginx
      path:
        - samples/data/nginx-access.log
  - file:
      routes:
        - idPrefix: "nginx-"
          labels:
            type: "error"
      labels:
        name: acmehost
        type: Nginx
      path:
        - samples/data/nginx-error.log
