backends:
  - opensearch:
      address: "https://logs.example.com"
      namespace: "kube"
      fields:
        message: "message"
        timestamp: "@timestamp"
        exclusions:
          - "log"
      username: 
        value: "elastic"
      password:
        value: "abcdefghijklmnopqrstuvwxyz"
      index: "my-index-*"
      query: '
        {
          "search_after": {{.Page}},
          "sort": [
            {
              "@timestamp": {
                "order": "desc",
                "unmapped_type": "boolean"
              }
            }
          ],
          "query": { 
            "match_phrase" : {
              "transaction.client_ip": "{{index .Labels "clientIP"}}"
            }
          }
        }'
