# Default values for apm-hub.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

nameOverride: ""

deployment:
  label: apm-hub

image:
  repository: docker.io/flanksource/apm-hub
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "latest"

serviceAccount:
  # Annotations to add to the service account
  annotations: {}

service:
  type: ClusterIP
  port: 8080
  targetPort: 8080
  protocol: TCP

configYaml: |
  backends:
    - kubernetes:
        kubeconfig:

ingress:
  enabled: false
  className: ""
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

resources: 
  requests:
    cpu: 200m
    memory: 200Mi
  limits:
    cpu: 500m
    memory: 512Mi

extras:
  imagePullSecrets: []
  podAnnotations: {}
  podSecurityContext: {}
    # fsGroup: 2000
  securityContext: {}
    # capabilities:
    #   drop:
    #   - ALL
    # readOnlyRootFilesystem: true
    # runAsNonRoot: true
    # runAsUser: 1000
  nodeSelector: {}
  tolerations: []
  affinity: {}

