apiVersion: apm-hub.flanksource.com/v1
kind: LoggingBackend
metadata:
  name: file-backend
spec:
  backends:
  - file:
    - labels:
        name: acmehost
        type: Nginx
      path:
      - nginx-access.log
    - labels:
        name: all
        type: Nginx
      path:
        - "*.log"
