on: pull_request
name: Build
# Declare default permissions as read only
permissions: read-all
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@9bb56186c3b09b4f86b1c65136769dd318469633 # v4.1.2
      - name: Build Container
        run: make docker
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
