on: pull_request
name: Build
# Declare default permissions as read only
permissions: read-all
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@1d96c772d19495a3b5c517cd2bc0cb401ea0529f # v4.1.3
      - name: Build Container
        run: make docker
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
