on:
  pull_request:

name: Test
permissions:
  contents: read
  checks: write
  issues: write
  pull-requests: write
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@fac708d6674e30b6ba41289acaab6d4b75aa0753 # v4.0.1
        with:
          go-version: 1.20.x
      - name: Checkout code
        uses: actions/checkout@9bb56186c3b09b4f86b1c65136769dd318469633 # v4.1.2
      - name: Test
        run: make test
      - name: Publish Test Results
        uses: EnricoMi/publish-unit-test-result-action@f0b5d2433f350eff587831d4ad22cb15aab75866 # v2.8.0
        if: always()
        with:
          files: test/test-results.xml
          check_name: E2E - ${{matrix.suite}}
